version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  axon:
    image: axoniq/axonserver
    ports:
      - '8024:8024'
      - '8124:8124'